use_frameworks!
platform :ios, '11.0'

target 'SCKTEffects-Example' do
  pod 'SCKTEffectsSpriteKit', :path => '../'
  pod 'SCKTEffectsSceneKit', :path => '../'
  pod 'SCKTEffectsCore', :path => '../'
end
